#!/bin/bash
export PATH=/usr/local/bin:/usr/bin:/bin
export YARP_CONFIG_HOME=/home/pi/.config/yarp
yarp detect --write
yarpdev --from /usr/local/share/robotDevastation-robots/contexts/launch/launchCamera.ini
sleep 1
